apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: patch-lightspeed-stack-config.yaml
  - path: patch-run-config.yaml
  - path: patch-deployment.yaml
images:
  - name: quay.io/lightspeed-core/lightspeed-stack
    newName: quay.io/lightspeed-core/lightspeed-stack
    newTag: dev-latest
namespace: konflux-lightspeed
