apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: patch-lightspeed-stack-config.yaml
  - path: patch-run-config.yaml
  - path: patch-deployment.yaml
images:
  - name: quay.io/lightspeed-core/lightspeed-stack
    newName: quay.io/lightspeed-core/lightspeed-stack
    # lightspeed-stack 0.7.0
    digest: sha256:159f3fb24ed16f026b1a8b9dc035ae122ae8d9897ed2403e4114dce070932ba1
namespace: konflux-lightspeed
