apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: patch-lightspeed-stack-config.yaml
  - path: patch-run-config.yaml
  - path: patch-deployment.yaml
images:
  - name: quay.io/lightspeed-core/lightspeed-stack
    newName: quay.io/lightspeed-core/lightspeed-stack
    # lightspeed-stack 0.6.2
    digest: sha256:1317d65e10c34183de36144a8c9effc81a28aacae62f5ba6be448b60ff6cc10d
namespace: konflux-lightspeed
